# **Notebook 01** - Exploração Inicial dos Dados

### Objetivo

O objetivo deste notebook é realizar uma exploração inicial dos dados de viagens da Cyclistic, buscando compreender sua estrutura, características e principais variáveis antes da etapa de limpeza e preparação dos dados.

### Etapas

Neste notebook serão realizadas as seguintes etapas:

*1. Importação das bibliotecas necessárias;*<br>
*2. Carregamento dos arquivos mensais;*<br>
*3. Verificação da quantidade de registros e colunas;*<br>
*4. Identificação e compreensão das variáveis disponíveis;*<br>
*5. Verificação dos tipos de dados;*<br>
*6. Inspeção inicial dos registros;*<br>
*7. Comparação da estrutura dos diferentes arquivos mensais;*<br>
*8. Concatenação dos datasets em um único DataFrame;*<br>
*9. Salvamento do dataset consolidado para utilização nas etapas seguintes.*<br>

> **Observação:** Esta etapa tem como foco compreender os dados e identificar possíveis problemas. Questões relacionadas à qualidade dos dados, como valores ausentes, duplicidades, inconsistências e erros de tipagem, serão investigadas e tratadas no próximo notebook.

---

## 1. Importação das Bibliotecas

In [1]:
# Imports

import pandas as pd

---

## 2. Carregamento dos Dados

In [2]:
# Cria string com data de identificação do arquivo/variavel

def str_date(i):
    if i < 4:
        year = 2025
        month = i + 9
    else:
        year = 2026
        month = i - 3

    return f"{year}{month:02d}"

In [3]:
# Cria Dicionario de com os 12 Datasets 

datasets = {}

for i in range(12):
    
    file_name = f"{str_date(i)}-divvy-tripdata.csv"

    datasets[f"{str_date(i)}"] = pd.read_csv(
        f"../data/raw/{file_name}"
    )

---

## 3. Exploração Inicial dos Datasets

In [4]:
for name, df in datasets.items():
    
    print(f"\n{'=' * 50}")
    print(f"DATASET: {name}")
    print(f"{'=' * 50}")

    display(df.head())
    print('\n')

==================================================
DATASET: 202509
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,B0AD82B8A2556E7C,electric_bike,2025-09-01 12:05:13.323,2025-09-01 12:25:19.273,NaN,NaN,NaN,NaN,41.91,-87.63,41.96,-87.64,member
1,DCC4ABF0F7DCCE6A,electric_bike,2025-09-01 01:41:00.775,2025-09-01 01:48:59.228,NaN,NaN,NaN,NaN,41.95,-87.67,41.95,-87.65,member
2,C27785FFE7568433,electric_bike,2025-09-01 07:16:13.921,2025-09-01 07:39:51.831,NaN,NaN,NaN,NaN,41.94,-87.65,41.98,-87.65,member
3,812DB2D3AD2F18EB,electric_bike,2025-09-01 09:31:36.294,2025-09-01 09:49:08.022,NaN,NaN,NaN,NaN,41.98,-87.65,41.94,-87.65,member
4,61F6BD3174DC4E84,electric_bike,2025-09-26 08:51:58.069,2025-09-26 09:07:29.290,NaN,NaN,NaN,NaN,41.90,-87.69,41.87,-87.65,member

==================================================
DATASET: 202510
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,AAED255E1310E516,classic_bike,2025-10-27 08:19:53.208,2025-10-27 08:25:53.481,Wells St & Polk St,CHI00606,Franklin St & Washington St,CHI02074,41.872732,-87.633516,41.883180,-87.635110,member
1,F90C86BF3BB85040,classic_bike,2025-10-14 07:42:55.465,2025-10-14 08:04:08.663,Racine Ave & Wrightwood Ave,CHI00506,McClurg Ct & Ohio St,CHI00330,41.928887,-87.658971,41.892592,-87.617289,member
2,90429D9729A3EE8E,classic_bike,2025-10-12 08:18:23.613,2025-10-12 08:28:38.983,Clinton St & 18th St,CHI00235,Desplaines St & Jackson Blvd,CHI00518,41.857950,-87.640826,41.878119,-87.643948,casual
3,C8433F9B78A1E63D,electric_bike,2025-10-14 07:45:56.471,2025-10-14 08:07:24.447,Pine Grove Ave & Irving Park Rd,CHI00482,Wells St & Huron St,CHI00294,41.954398,-87.647997,41.894795,-87.634374,member
4,62F3C413C442C154,electric_bike,2025-10-19 10:08:45.138,2025-10-19 10:12:34.771,Pine Grove Ave & Irving Park Rd,CHI00482,Sheridan Rd & Montrose Ave,CHI00290,41.954365,-87.647929,41.961670,-87.654640,member

==================================================
DATASET: 202511
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E555D9F8E9C2F56B,electric_bike,2025-11-04 00:09:07.792,2025-11-04 00:15:04.661,NaN,NaN,NaN,NaN,41.94,-87.67,41.94,-87.67,casual
1,EAEBE70DBF015886,electric_bike,2025-11-04 14:32:09.067,2025-11-04 14:36:43.998,NaN,NaN,NaN,NaN,41.90,-87.64,41.91,-87.64,casual
2,A42F8404F804E56E,electric_bike,2025-11-04 12:20:48.215,2025-11-04 12:21:01.630,NaN,NaN,NaN,NaN,41.89,-87.63,41.89,-87.63,casual
3,E49D01E38A1E074E,electric_bike,2025-11-04 12:17:16.548,2025-11-04 12:17:51.527,NaN,NaN,NaN,NaN,41.89,-87.63,41.89,-87.63,casual
4,9308F609195D2414,electric_bike,2025-11-04 08:16:27.979,2025-11-04 08:21:02.780,NaN,NaN,NaN,NaN,41.89,-87.64,41.88,-87.64,casual

==================================================
DATASET: 202512
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,D90034EFC7235A41,electric_bike,2025-12-22 17:20:27.872,2025-12-22 17:27:29.937,Broadway & Berwyn Ave,CHI00414,Broadway & Sunnyside Ave,CHI02089,41.978361,-87.659789,41.963419,-87.656069,member
1,B005230EE77A29D0,classic_bike,2025-12-20 17:15:31.749,2025-12-20 17:20:07.746,Sheridan Rd & Montrose Ave,CHI00290,Broadway & Sheridan Rd,CHI00476,41.961670,-87.654640,41.952833,-87.649993,member
2,FD33124F2231E215,classic_bike,2025-12-06 13:38:18.275,2025-12-06 13:52:54.682,Southport Ave & Wrightwood Ave,CHI00339,Larrabee St & Menomonee St,CHI00262,41.928773,-87.663913,41.914680,-87.643320,casual
3,7363165DB4BD6D14,electric_bike,2025-12-16 20:58:28.703,2025-12-16 21:04:35.476,Sheridan Rd & Montrose Ave,CHI00290,Clark St & Newport St,CHI00674,41.961670,-87.654640,41.944540,-87.654678,member
4,F09F745E43DF9556,electric_bike,2025-12-09 14:53:43.347,2025-12-09 14:58:30.944,Larrabee St & Kingsbury St 1,CHI00245,Rush St & Superior St,CHI00368,41.897764,-87.642884,41.895765,-87.625908,member

==================================================
DATASET: 202601
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,FD0EB1D32AF0D47E,classic_bike,2026-01-31 09:13:09.018,2026-01-31 09:28:10.302,Central St & Girard Ave,CHI02042,Dodge Ave & Church St,CHI00741,42.064313,-87.686152,42.048308,-87.698224,member
1,FB27405C3F8C824F,classic_bike,2026-01-15 14:25:42.526,2026-01-15 14:33:18.854,Shore Dr & 55th St,CHI00394,Woodlawn Ave & 55th St,CHI00423,41.795212,-87.580715,41.795264,-87.596471,casual
2,6FAFA1709403AA27,electric_bike,2026-01-06 12:55:33.572,2026-01-06 13:02:17.922,Hampden Ct & Diversey Pkwy,CHI02087,NaN,NaN,41.932470,-87.642420,41.940000,-87.640000,member
3,1F34C1FAD9FEC2D8,electric_bike,2026-01-26 16:22:25.011,2026-01-26 16:53:15.197,Carpenter St & Huron St,CHI00286,NaN,NaN,41.894532,-87.653412,41.830000,-87.670000,member
4,8E3E3072D8D3D918,electric_bike,2026-01-10 18:13:30.139,2026-01-10 19:31:56.971,Clinton St & Madison St,CHI00233,NaN,NaN,41.881660,-87.641150,41.890000,-87.630000,member

==================================================
DATASET: 202602
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4194C9D5CAFDBE7C,electric_bike,2026-02-08 17:08:34.392,2026-02-08 17:13:57.661,NaN,NaN,NaN,NaN,41.95,-87.65,41.96,-87.65,member
1,790A93E87E5EE83C,electric_bike,2026-02-08 14:44:11.880,2026-02-08 14:48:14.329,NaN,NaN,NaN,NaN,41.89,-87.62,41.89,-87.62,member
2,21ABD91CD9FB7D13,electric_bike,2026-02-08 14:38:03.488,2026-02-08 14:41:19.976,NaN,NaN,NaN,NaN,41.94,-87.67,41.94,-87.66,member
3,8D97FE9075293A3B,electric_bike,2026-02-07 19:20:35.501,2026-02-07 19:20:58.619,NaN,NaN,NaN,NaN,41.90,-87.63,41.90,-87.63,member
4,03A65D965372A020,electric_bike,2026-02-07 20:47:02.949,2026-02-07 20:47:18.752,NaN,NaN,NaN,NaN,41.89,-87.62,41.89,-87.62,member

==================================================
DATASET: 202603
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,AE72B07EAC06D106,classic_bike,2026-03-20 09:07:13.866,2026-03-20 09:11:33.295,Chicago Ave & Sheridan Rd,CHI02043,Sheridan Rd & Noyes St (NU),CHI01114,42.050491,-87.677821,42.058239,-87.677432,member
1,2FC08B198BA431AA,classic_bike,2026-03-31 13:35:55.605,2026-03-31 13:39:31.356,Morgan St & Polk St,CHI00372,Loomis St & Lexington St,CHI00238,41.871737,-87.651030,41.872229,-87.661364,member
2,9360F18B10C847D9,electric_bike,2026-03-19 16:40:45.321,2026-03-19 16:43:28.905,Morgan St & Polk St,CHI00372,Loomis St & Lexington St,CHI00238,41.871737,-87.651030,41.872229,-87.661364,member
3,946494EB892374E9,classic_bike,2026-03-09 14:15:57.612,2026-03-09 14:21:38.563,Damen Ave & Pierce Ave,CHI02057,Damen Ave & Charleston St,CHI00403,41.909358,-87.677758,41.920082,-87.677855,member
4,6EE0E2DA57702502,electric_bike,2026-03-17 08:26:04.840,2026-03-17 08:26:12.374,Sheffield Ave & Webster Ave,CHI00507,Sheffield Ave & Webster Ave,CHI00507,41.921540,-87.653818,41.921540,-87.653818,member

==================================================
DATASET: 202604
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9B9C7B1E3F4FC96C,electric_bike,2026-04-13 14:47:32.170,2026-04-13 14:48:57.868,NaN,NaN,NaN,NaN,41.96,-87.65,41.96,-87.65,member
1,8FE476DD539B3402,electric_bike,2026-04-13 09:56:56.062,2026-04-13 10:24:12.047,NaN,NaN,NaN,NaN,41.91,-87.66,41.88,-87.63,member
2,CFA502A5FDC3E2D6,electric_bike,2026-04-13 08:33:39.927,2026-04-13 08:55:36.991,NaN,NaN,NaN,NaN,41.96,-87.65,41.91,-87.66,member
3,AE6216BBF65C38AC,electric_bike,2026-04-13 12:04:56.051,2026-04-13 12:31:00.820,NaN,NaN,NaN,NaN,41.88,-87.63,41.96,-87.65,member
4,65C4A1F96AA07A5A,electric_bike,2026-04-26 08:50:42.378,2026-04-26 08:56:44.514,NaN,NaN,NaN,NaN,41.93,-87.64,41.92,-87.64,member

==================================================
DATASET: 202605
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E8847A2B0FD51251,electric_bike,2026-05-20 11:36:57.782,2026-05-20 11:37:17.020,NaN,NaN,NaN,NaN,41.89,-87.62,41.89,-87.62,casual
1,746948BC4E29B6D0,electric_bike,2026-05-20 11:37:45.232,2026-05-20 11:51:43.399,NaN,NaN,NaN,NaN,41.89,-87.62,41.90,-87.64,casual
2,33E3CE21C190985E,electric_bike,2026-05-20 18:37:05.606,2026-05-20 18:48:39.956,NaN,NaN,NaN,NaN,41.91,-87.63,41.93,-87.64,casual
3,63D3912D5A15ED09,electric_bike,2026-05-20 08:00:52.487,2026-05-20 08:09:58.630,NaN,NaN,NaN,NaN,41.91,-87.63,41.89,-87.64,casual
4,76EBC4E28ABC6A5E,electric_bike,2026-05-19 19:39:44.270,2026-05-19 20:06:45.976,NaN,NaN,NaN,NaN,41.91,-87.63,41.91,-87.63,casual

==================================================
DATASET: 202606
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A2C4781347F47E38,electric_bike,2026-06-14 11:23:31.606,2026-06-14 11:44:42.669,NaN,NaN,NaN,NaN,41.90,-87.68,41.90,-87.67,casual
1,415E1AB78BDE82D1,electric_bike,2026-06-14 17:13:17.473,2026-06-14 18:05:50.034,NaN,NaN,NaN,NaN,41.91,-87.63,41.88,-87.62,casual
2,97CCC9151C7608ED,electric_bike,2026-06-14 17:11:13.690,2026-06-14 17:11:56.203,NaN,NaN,NaN,NaN,41.91,-87.63,41.91,-87.63,casual
3,D738CEC0F7D23C0F,electric_bike,2026-06-13 22:32:22.653,2026-06-13 22:36:22.058,NaN,NaN,NaN,NaN,41.84,-87.72,41.84,-87.72,casual
4,354A481AD74AF840,electric_bike,2026-06-13 22:21:43.710,2026-06-13 22:24:40.841,NaN,NaN,NaN,NaN,41.93,-87.66,41.93,-87.65,casual

==================================================
DATASET: 202607
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,21025F24DBEF6519,electric_bike,2026-07-12 22:05:11.820,2026-07-12 22:05:39.379,NaN,NaN,NaN,NaN,41.83,-87.67,41.83,-87.67,casual
1,8082E8641F99942A,electric_bike,2026-07-12 20:35:32.267,2026-07-12 20:50:07.751,NaN,NaN,NaN,NaN,41.81,-87.61,41.79,-87.60,casual
2,342D8CF65B43B851,electric_bike,2026-07-13 16:05:24.933,2026-07-13 16:18:47.073,NaN,NaN,NaN,NaN,41.95,-87.73,41.91,-87.73,casual
3,DEA8B69B20D33726,electric_bike,2026-07-13 06:19:39.414,2026-07-13 06:31:20.421,NaN,NaN,NaN,NaN,41.95,-87.64,41.91,-87.63,casual
4,2008E2C3DB963718,electric_bike,2026-07-13 11:51:36.099,2026-07-13 11:52:00.176,NaN,NaN,NaN,NaN,41.88,-87.62,41.88,-87.62,casual

==================================================
DATASET: 202608
==================================================

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,B68574B42AE9F00F,electric_bike,2026-08-04 22:08:17.594,2026-08-04 22:28:42.843,NaN,NaN,NaN,NaN,41.91,-87.68,41.96,-87.68,member
1,32BE64BBA89A6249,electric_bike,2026-08-05 16:37:39.518,2026-08-05 16:52:01.740,NaN,NaN,NaN,NaN,41.92,-87.64,41.90,-87.64,member
2,BEF02F4CCEA3AC8B,electric_bike,2026-08-05 10:05:57.628,2026-08-05 10:11:51.226,NaN,NaN,NaN,NaN,41.89,-87.65,41.90,-87.65,member
3,7E0F8B8808F45C7E,electric_bike,2026-08-05 10:14:54.444,2026-08-05 10:19:51.347,NaN,NaN,NaN,NaN,41.90,-87.65,41.89,-87.65,member
4,46F1B20BEF5E0FE9,electric_bike,2026-08-10 15:13:47.747,2026-08-10 15:42:04.857,NaN,NaN,NaN,NaN,41.90,-87.68,41.89,-87.68,member

---

## 4. Estrutura e Variáveis

In [5]:
# Relatório do Shape de cada DataFrame 

for name, df in datasets.items():

    print(f"\n{'=' * 50}")
    print(f"DATASET: {name}")
    print(f"{'=' * 50}")
    
    print(f"Linhas: {df.shape[0]:,}")
    print(f"Colunas: {df.shape[1]}")

==================================================
DATASET: 202509
==================================================
Linhas: 714,759
Colunas: 13

==================================================
DATASET: 202510
==================================================
Linhas: 646,039
Colunas: 13

==================================================
DATASET: 202511
==================================================
Linhas: 356,628
Colunas: 13

==================================================
DATASET: 202512
==================================================
Linhas: 140,534
Colunas: 13

==================================================
DATASET: 202601
==================================================
Linhas: 137,787
Colunas: 13

==================================================
DATASET: 202602
==================================================
Linhas: 201,450
Colunas: 13

==================================================
DATASET: 202603
==================================================
Linhas: 317,037
Colunas: 13

==================================================
DATASET: 202604
==================================================
Linhas: 448,252
Colunas: 13

==================================================
DATASET: 202605
==================================================
Linhas: 653,704
Colunas: 13

==================================================
DATASET: 202606
==================================================
Linhas: 762,550
Colunas: 13

==================================================
DATASET: 202607
==================================================
Linhas: 869,051
Colunas: 13

==================================================
DATASET: 202608
==================================================
Linhas: 868,191
Colunas: 13

In [6]:
# Verificando tipos das Variaveis 

columns_type = {}

for name, df in datasets.items():

    columns = df.columns
    
    print(f"\n{'=' * 50}")
    print(f"DATASET: {name}")
    print(f"{'=' * 50}")

    for i in range(12): 

        columns_type[name] = {columns[i] : df[columns[i]].dtype}

        print(f"{columns[i]} : {df[columns[i]].dtype}")

==================================================
DATASET: 202509
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202510
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202511
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202512
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202601
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202602
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202603
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202604
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202605
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202606
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202607
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

==================================================
DATASET: 202608
==================================================
ride_id : str
rideable_type : str
started_at : str
ended_at : str
start_station_name : str
start_station_id : str
end_station_name : str
end_station_id : str
start_lat : float64
start_lng : float64
end_lat : float64
end_lng : float64

---

## 5. Comparação entre os Arquivos Mensais

In [7]:
# Checando se todos os DataFrames possuem as mesmas colunas 
# Se 'False' todas as colunas são iguais
 
columns = {}

for name, df in datasets.items():
    columns[name] = list(df.columns)

different_columns = len(set(map(tuple, columns.values()))) > 1

print(different_columns)

False

In [8]:
# Checando se alguma incongluencia nos tipos de variaveis em cada DataFrame
# Se 'False' todos os tipos são iguais para todas as colunas de todos dfs

different_columns_type = len(set(map(tuple, columns_type.values()))) > 1
print(different_columns_type)

False

---

## 6. Concatenação dos Datasets

In [9]:
# Concatenado DataFrames

df = pd.concat(datasets.values(), ignore_index=True)

In [10]:
# Checando a nova estrutura do Dataframe com todos os meses

df.shape

(6115982, 13)

In [11]:
# Explorando DataFrame com todos os meses

df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,B0AD82B8A2556E7C,electric_bike,2025-09-01 12:05:13.323,2025-09-01 12:25:19.273,NaN,NaN,NaN,NaN,41.91,-87.63,41.96,-87.64,member
1,DCC4ABF0F7DCCE6A,electric_bike,2025-09-01 01:41:00.775,2025-09-01 01:48:59.228,NaN,NaN,NaN,NaN,41.95,-87.67,41.95,-87.65,member
2,C27785FFE7568433,electric_bike,2025-09-01 07:16:13.921,2025-09-01 07:39:51.831,NaN,NaN,NaN,NaN,41.94,-87.65,41.98,-87.65,member
3,812DB2D3AD2F18EB,electric_bike,2025-09-01 09:31:36.294,2025-09-01 09:49:08.022,NaN,NaN,NaN,NaN,41.98,-87.65,41.94,-87.65,member
4,61F6BD3174DC4E84,electric_bike,2025-09-26 08:51:58.069,2025-09-26 09:07:29.290,NaN,NaN,NaN,NaN,41.90,-87.69,41.87,-87.65,member

In [12]:
# Comparando DataFrame com os 12 Meses em relação aos DataFrames De Meses Individuais

individual_total = sum(len(dataset) for dataset in datasets.values())

print(f"Total dos datasets: {individual_total:,}")
print(f"Total após concatenação: {len(df):,}")
print(f"Os valores são iguais? {individual_total == len(df)}")

Total dos datasets: 6,115,982
Total após concatenação: 6,115,982
Os valores são iguais? True

---

## 7. Salvando os Dados Consolidados

In [13]:
# Salvando .csv na pasta processed

df.to_csv("../data/processed/cyclistic_202509_202608.csv", index=False)